ALTER TABLE notification_reminder_dispatches ADD COLUMN IF NOT EXISTS business_key varchar(180) NOT NULL DEFAULT '';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS delivery_attempts integer NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS channel varchar(20) NOT NULL DEFAULT 'IN_APP';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS delivery_status varchar(20) NOT NULL DEFAULT 'CREATED';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS variables_json text DEFAULT '{}';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS delivery_error text;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS lease_until timestamptz;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE notifications ALTER COLUMN source_event_id DROP NOT NULL;
