package com.lmspilot.assessment.api;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lmspilot.assessment.api.AssessmentModels.*;
import com.lmspilot.assessment.domain.*;
import com.lmspilot.assessment.platform.*;
import com.lmspilot.support.api.ApiException;
import com.lmspilot.support.security.CurrentUser;
import java.time.*; import java.util.*; import java.util.stream.Collectors;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class AssessmentManagementService {
 private final QuestionRepository questions; private final ExamRepository exams; private final ExamQuestionRepository examQuestions; private final ExamSessionRepository sessions; private final ExamSessionEventRepository sessionEvents; private final AssessmentContextRepository contexts; private final AssessmentAssignmentRepository assignments; private final CompetitionRepository competitions; private final CompetitionLeaderboardRepository leaderboard; private final CompetitionRewardRepository rewards; private final RewardLedgerRepository ledger; private final QuestionProvenanceRepository provenance; private final ObjectMapper mapper;
 public AssessmentManagementService(QuestionRepository questions,ExamRepository exams,ExamQuestionRepository examQuestions,ExamSessionRepository sessions,ExamSessionEventRepository sessionEvents,AssessmentContextRepository contexts,AssessmentAssignmentRepository assignments,CompetitionRepository competitions,CompetitionLeaderboardRepository leaderboard,CompetitionRewardRepository rewards,RewardLedgerRepository ledger,QuestionProvenanceRepository provenance,ObjectMapper mapper){this.questions=questions;this.exams=exams;this.examQuestions=examQuestions;this.sessions=sessions;this.sessionEvents=sessionEvents;this.contexts=contexts;this.assignments=assignments;this.competitions=competitions;this.leaderboard=leaderboard;this.rewards=rewards;this.ledger=ledger;this.provenance=provenance;this.mapper=mapper;}
 private UUID actor(){return CurrentUser.id();}
 private ApiException missing(String code,String message){return new ApiException(HttpStatus.NOT_FOUND,code,message);}
 private List<String> list(String json){try{return mapper.readValue(json,new TypeReference<List<String>>(){});}catch(Exception e){return List.of();}}
 private Map<String,JsonNode> answers(String json){try{return mapper.readValue(json,new TypeReference<Map<String,JsonNode>>(){});}catch(Exception e){return Map.of();}}
 private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_JSON","Dữ liệu không hợp lệ");}}
 private void owner(UUID id){if(!Objects.equals(id,actor())) throw new ApiException(HttpStatus.FORBIDDEN,"OUT_OF_SCOPE","Dữ liệu ngoài phạm vi quản lý");}
 private void validateQuestion(QuestionRequest i){if(i.type()==null||i.prompt()==null||i.prompt().isBlank()) throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_QUESTION","Câu hỏi không hợp lệ"); if((i.type()==QuestionType.SINGLE_CHOICE||i.type()==QuestionType.MULTIPLE_CHOICE||i.type()==QuestionType.TRUE_FALSE)&&(i.options().size()<2||i.correctAnswers().isEmpty())) throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTIONS","Câu hỏi khách quan cần phương án và đáp án đúng"); if(!i.options().containsAll(i.correctAnswers())) throw new ApiException(HttpStatus.BAD_REQUEST,"ANSWER_NOT_IN_OPTIONS","Đáp án đúng phải thuộc danh sách phương án");}
 private QuestionResponse q(QuestionEntity e){return new QuestionResponse(e.id,e.type,e.prompt,list(e.optionsJson),list(e.correctAnswersJson),e.explanation,e.difficulty,Arrays.stream(e.tagsCsv.split(",")).filter(s->!s.isBlank()).collect(Collectors.toCollection(LinkedHashSet::new)),e.defaultPoints,e.status,e.questionVersion);}
 @Transactional(readOnly=true) public List<QuestionResponse> listQuestions(){return questions.findAllByOwnerIdOrderByUpdatedAtDesc(actor()).stream().filter(x->x.status!=QuestionStatus.ARCHIVED).map(this::q).toList();}
 @Transactional public QuestionResponse createQuestion(QuestionRequest i){validateQuestion(i);QuestionEntity e=new QuestionEntity();e.ownerId=actor();e.type=i.type();e.prompt=i.prompt().trim();e.optionsJson=json(i.options().stream().map(String::trim).toList());e.correctAnswersJson=json(i.correctAnswers().stream().map(String::trim).toList());e.explanation=i.explanation();e.difficulty=i.difficulty();e.tagsCsv=String.join(",",i.tags());e.defaultPoints=i.defaultPoints();return q(questions.save(e));}
 @Transactional public QuestionResponse updateQuestion(UUID id,QuestionRequest i){validateQuestion(i);QuestionEntity e=questions.findById(id).orElseThrow(()->missing("QUESTION_NOT_FOUND","Không tìm thấy câu hỏi"));owner(e.ownerId);e.type=i.type();e.prompt=i.prompt().trim();e.optionsJson=json(i.options());e.correctAnswersJson=json(i.correctAnswers());e.explanation=i.explanation();e.difficulty=i.difficulty();e.tagsCsv=String.join(",",i.tags());e.defaultPoints=i.defaultPoints();e.questionVersion++;e.updatedAt=Instant.now();return q(e);}
 @Transactional public void archiveQuestion(UUID id){QuestionEntity e=questions.findById(id).orElseThrow(()->missing("QUESTION_NOT_FOUND","Không tìm thấy câu hỏi"));owner(e.ownerId);e.status=QuestionStatus.ARCHIVED;e.updatedAt=Instant.now();}
 private AssessmentContextType inferred(ExamEntity e){return contexts.findById(e.id).map(c->c.contextType).orElse(e.courseId==null?AssessmentContextType.STANDALONE_EXAM:AssessmentContextType.COURSE_QUIZ);}
 private ExamResponse exam(ExamEntity e){AssessmentContextEntity c=contexts.findById(e.id).orElse(null);List<ExamQuestionView> views=examQuestions.findAllByExamIdOrderBySortOrderAsc(e.id).stream().map(x->new ExamQuestionView(x.questionId,x.type,x.promptSnapshot,list(x.optionsSnapshotJson),x.points,x.sortOrder)).toList();return new ExamResponse(e.id,e.title,e.courseId,e.lessonId,c==null?inferred(e):c.contextType,c==null?null:c.cohortId,c==null||c.autoGrade,e.durationMinutes,e.opensAt,e.closesAt,e.maxAttempts,e.waitMinutesBetweenAttempts,e.passingScore,e.shuffleQuestions,e.shuffleAnswers,e.scoreStrategy,e.status,e.examVersion,views);}
 @Transactional(readOnly=true) public List<ExamResponse> listExams(){List<ExamEntity> all=CurrentUser.hasRole("STUDENT")?exams.findAllByStatusOrderByUpdatedAtDesc(ExamStatus.ACTIVE):exams.findAll();return all.stream().filter(e->e.status!=ExamStatus.ARCHIVED).sorted(Comparator.comparing((ExamEntity e)->e.updatedAt).reversed()).map(this::exam).toList();}
 @Transactional(readOnly=true) public ExamResponse getExam(UUID id){return exam(exams.findById(id).orElseThrow(()->missing("EXAM_NOT_FOUND","Không tìm thấy bài thi")));}
 private AssessmentContextSpec spec(ExamRequest i){AssessmentContextType t=i.contextType()!=null?i.contextType():(i.courseId()!=null?AssessmentContextType.COURSE_QUIZ:AssessmentContextType.STANDALONE_EXAM);try{return new AssessmentContextSpec(t,i.courseId(),i.cohortId(),i.opensAt(),i.closesAt(),i.maxAttempts(),i.autoGrade());}catch(IllegalArgumentException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_ASSESSMENT_CONTEXT",e.getMessage());}}
 private void apply(ExamEntity e,ExamRequest i){AssessmentContextSpec s=spec(i);e.title=i.title().trim();e.courseId=i.courseId();e.lessonId=i.lessonId();e.durationMinutes=i.durationMinutes();e.opensAt=i.opensAt();e.closesAt=i.closesAt();e.maxAttempts=i.maxAttempts();e.waitMinutesBetweenAttempts=i.waitMinutesBetweenAttempts();e.passingScore=i.passingScore();e.shuffleQuestions=i.shuffleQuestions();e.shuffleAnswers=i.shuffleAnswers();e.scoreStrategy=i.scoreStrategy()==null?ScoreStrategy.HIGHEST:i.scoreStrategy();e.status=i.status()==null?ExamStatus.DRAFT:i.status();e.updatedAt=Instant.now();AssessmentContextEntity c=contexts.findById(e.id).orElseGet(AssessmentContextEntity::new);c.assessmentId=e.id;c.contextType=s.type();c.courseId=s.courseId();c.cohortId=s.cohortId();c.opensAt=s.opensAt();c.closesAt=s.closesAt();c.maxAttempts=s.maxAttempts();c.autoGrade=s.autoGrade();contexts.save(c);}
 private void snapshot(ExamEntity e,List<ExamQuestionInput> inputs){examQuestions.deleteAllByExamId(e.id);if(inputs==null)return;Set<UUID> seen=new HashSet<>();for(ExamQuestionInput in:inputs){if(!seen.add(in.questionId()))throw new ApiException(HttpStatus.BAD_REQUEST,"DUPLICATE_QUESTION","Một câu hỏi xuất hiện nhiều lần");QuestionEntity q=questions.findById(in.questionId()).orElseThrow(()->missing("QUESTION_NOT_FOUND","Không tìm thấy câu hỏi"));ExamQuestionEntity x=new ExamQuestionEntity();x.examId=e.id;x.questionId=q.id;x.questionVersion=q.questionVersion;x.type=q.type;x.promptSnapshot=q.prompt;x.optionsSnapshotJson=q.optionsJson;x.correctAnswersSnapshotJson=q.correctAnswersJson;x.points=in.points();x.sortOrder=in.sortOrder();examQuestions.save(x);}}
 @Transactional public ExamResponse createExam(ExamRequest i){ExamEntity e=new ExamEntity();e.ownerId=actor();apply(e,i);exams.save(e);apply(e,i);snapshot(e,i.questions());if(inferred(e)==AssessmentContextType.COMPETITION){CompetitionEntity c=new CompetitionEntity();c.assessmentId=e.id;competitions.save(c);}return exam(e);}
 @Transactional public ExamResponse updateExam(UUID id,ExamRequest i){ExamEntity e=exams.findById(id).orElseThrow(()->missing("EXAM_NOT_FOUND","Không tìm thấy bài thi"));owner(e.ownerId);if(sessions.existsByExamId(id)&&e.status==ExamStatus.ACTIVE) throw new ApiException(HttpStatus.CONFLICT,"EXAM_ALREADY_ATTEMPTED","Bài thi đã có lượt làm; hãy tạo phiên bản mới");apply(e,i);e.examVersion++;snapshot(e,i.questions());return exam(e);}
 @Transactional public void archiveExam(UUID id){ExamEntity e=exams.findById(id).orElseThrow(()->missing("EXAM_NOT_FOUND","Không tìm thấy bài thi"));owner(e.ownerId);e.status=ExamStatus.ARCHIVED;e.updatedAt=Instant.now();}
 @Transactional public SessionResponse start(StartSessionRequest i){ExamEntity e=exams.findStartSnapshotById(i.examId()).orElseThrow(()->missing("EXAM_NOT_FOUND","Không tìm thấy bài thi"));Instant now=Instant.now();if(e.status!=ExamStatus.ACTIVE||e.opensAt!=null&&e.opensAt.isAfter(now)||e.closesAt!=null&&e.closesAt.isBefore(now))throw new ApiException(HttpStatus.CONFLICT,"EXAM_NOT_OPEN","Bài thi chưa mở hoặc đã đóng");UUID u=actor();List<ExamSessionEntity> history=i.enrollmentId()==null?sessions.findAllByExamIdAndUserIdAndEnrollmentIdIsNullOrderByAttemptNoAsc(e.id,u):sessions.findAllByExamIdAndEnrollmentIdOrderByAttemptNoAsc(e.id,i.enrollmentId());for(ExamSessionEntity s:history)if(s.status==ExamSessionStatus.IN_PROGRESS&&s.graceUntil.isAfter(now))return session(s);if(history.size()>=e.maxAttempts)throw new ApiException(HttpStatus.CONFLICT,"ATTEMPT_LIMIT","Bạn đã hết số lần làm bài");ExamSessionEntity s=new ExamSessionEntity();s.examId=e.id;s.examVersion=e.examVersion;s.userId=u;s.enrollmentId=i.enrollmentId();s.courseId=e.courseId;s.lessonId=e.lessonId;s.attemptNo=history.size()+1;s.startedAt=now;s.expiresAt=now.plusSeconds(e.durationMinutes*60L);s.graceUntil=s.expiresAt.plusSeconds(120);s.lastHeartbeatAt=now;return session(sessions.save(s));}
 private SessionResponse session(ExamSessionEntity s){return new SessionResponse(s.id,s.examId,s.enrollmentId,s.courseId,s.lessonId,s.attemptNo,s.status,s.startedAt,s.expiresAt,s.graceUntil,s.lastHeartbeatAt,s.suspiciousEventCount,s.submittedAt,answers(s.answersJson),exam(exams.findById(s.examId).orElseThrow()).questions());}
 private ExamSessionEntity owned(UUID id){ExamSessionEntity s=sessions.findForUpdateById(id).orElseThrow(()->missing("SESSION_NOT_FOUND","Không tìm thấy phiên thi"));if(!Objects.equals(s.userId,actor()))throw new ApiException(HttpStatus.FORBIDDEN,"SESSION_FORBIDDEN","Phiên thi không thuộc tài khoản hiện tại");return s;}
 @Transactional public SessionResponse resume(UUID id){return session(owned(id));}
 @Transactional public SessionResponse heartbeat(UUID id){ExamSessionEntity s=owned(id);if(s.status==ExamSessionStatus.IN_PROGRESS)s.lastHeartbeatAt=Instant.now();return session(s);}
 @Transactional public SessionResponse save(UUID id,SaveAnswersRequest i){ExamSessionEntity s=owned(id);if(s.status!=ExamSessionStatus.IN_PROGRESS)throw new ApiException(HttpStatus.CONFLICT,"SESSION_LOCKED","Phiên thi đã khóa");Set<String> allowed=examQuestions.findAllByExamIdOrderBySortOrderAsc(s.examId).stream().map(x->x.questionId.toString()).collect(Collectors.toSet());if(!allowed.containsAll(i.answers().keySet()))throw new ApiException(HttpStatus.BAD_REQUEST,"ANSWER_QUESTION_MISMATCH","Đáp án chứa câu hỏi không thuộc phiên thi");String value=json(i.answers());if(value.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>1_048_576)throw new ApiException(HttpStatus.PAYLOAD_TOO_LARGE,"ANSWERS_TOO_LARGE","Dữ liệu đáp án vượt quá 1 MiB");s.answersJson=value;s.updatedAt=Instant.now();return session(s);}
 @Transactional public SessionResponse submit(UUID id,String key){if(key==null||key.isBlank()||key.length()>160)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_IDEMPOTENCY_KEY","Idempotency-Key không hợp lệ");Optional<ExamSessionEntity> old=sessions.findBySubmitIdempotencyKey(key);if(old.isPresent())return session(old.get());ExamSessionEntity s=owned(id);s.status=ExamSessionStatus.SUBMITTED;s.submittedAt=Instant.now();s.submitIdempotencyKey=key;s.updatedAt=Instant.now();return session(s);}
 @Transactional public SessionEventResponse event(UUID id,SessionEventRequest i){ExamSessionEntity s=owned(id);ExamSessionEventEntity e=new ExamSessionEventEntity();e.sessionId=s.id;e.userId=s.userId;e.type=i.type();e.details=i.details();e.occurredAt=i.occurredAt()==null?Instant.now():i.occurredAt();if(e.type!=ExamSessionEventType.HEARTBEAT)s.suspiciousEventCount++;sessionEvents.save(e);return new SessionEventResponse(e.id,e.type,e.details,e.occurredAt,e.storedAt);}
 @Transactional(readOnly=true) public List<SessionEventResponse> events(UUID id){ExamSessionEntity s=owned(id);return sessionEvents.findAllBySessionIdOrderByOccurredAtAsc(s.id).stream().map(e->new SessionEventResponse(e.id,e.type,e.details,e.occurredAt,e.storedAt)).toList();}
 @Transactional(readOnly=true) public GradingPayload grading(UUID id){ExamSessionEntity s=sessions.findById(id).orElseThrow(()->missing("SESSION_NOT_FOUND","Không tìm thấy phiên thi"));ExamEntity e=exams.findById(s.examId).orElseThrow();AssessmentContextEntity c=contexts.findById(e.id).orElse(null);List<GradingQuestionPayload> qs=examQuestions.findAllByExamIdOrderBySortOrderAsc(e.id).stream().map(q->new GradingQuestionPayload(q.questionId,q.type,q.promptSnapshot,list(q.correctAnswersSnapshotJson),q.points)).toList();return new GradingPayload(s.id,e.id,s.userId,e.passingScore,answers(s.answersJson),qs,s.enrollmentId,s.courseId,s.lessonId,c==null||c.autoGrade,c==null?inferred(e):c.contextType,e.scoreStrategy,Duration.between(s.startedAt,s.submittedAt==null?Instant.now():s.submittedAt).toMillis(),s.submittedAt);}
 @Transactional public void markGraded(UUID id){ExamSessionEntity s=sessions.findById(id).orElseThrow(()->missing("SESSION_NOT_FOUND","Không tìm thấy phiên thi"));s.status=ExamSessionStatus.GRADED;s.updatedAt=Instant.now();}
 @Transactional public List<QuestionResponse> importGenerated(List<GeneratedQuestionImport> items){List<QuestionResponse> result=new ArrayList<>();for(GeneratedQuestionImport i:items){QuestionRequest qr=new QuestionRequest(i.type(),i.prompt(),i.options(),i.correctAnswers(),i.explanation(),i.difficulty(),i.tags(),i.points());QuestionResponse saved=createQuestion(qr);QuestionProvenanceEntity p=new QuestionProvenanceEntity();p.questionId=saved.id();p.courseId=i.courseId();p.externalId=i.externalId();p.citationsJson=json(i.citations());p.sourceDocumentVersionsJson=json(i.sourceDocumentVersions());p.generatorMetadataJson=json(i.generatorMetadata());p.importedBy=actor();provenance.save(p);result.add(saved);}return result;}
 @Transactional public AssignmentResponse assign(UUID assessmentId,AssignmentRequest i){if(i.dueAt()!=null&&i.availableFrom()!=null&&!i.dueAt().isAfter(i.availableFrom()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_ASSIGNMENT_WINDOW","Hạn nộp phải sau thời gian mở");AssessmentAssignmentEntity e=assignments.findByAssessmentIdAndAssigneeTypeAndAssigneeId(assessmentId,i.assigneeType(),i.assigneeId()).orElseGet(AssessmentAssignmentEntity::new);e.assessmentId=assessmentId;e.assigneeType=i.assigneeType();e.assigneeId=i.assigneeId();e.availableFrom=i.availableFrom();e.dueAt=i.dueAt();e.required=i.required();e.status=AssessmentAssignmentStatus.ACTIVE;e.assignedBy=actor();e.updatedAt=Instant.now();return assignment(assignments.save(e));}
 private AssignmentResponse assignment(AssessmentAssignmentEntity e){return new AssignmentResponse(e.id,e.assessmentId,e.assigneeType,e.assigneeId,e.availableFrom,e.dueAt,e.required,e.status,e.assignedBy,e.assignedAt);}
 @Transactional(readOnly=true) public List<AssignmentResponse> assignments(UUID id){return assignments.findAllByAssessmentIdOrderByAssignedAtDesc(id).stream().map(this::assignment).toList();}
 @Transactional(readOnly=true) public List<AssignmentResponse> myAssignments(){return assignments.findAllByAssigneeTypeAndAssigneeIdAndStatusOrderByAssignedAtDesc(AssessmentAssigneeType.USER,actor(),AssessmentAssignmentStatus.ACTIVE).stream().map(this::assignment).toList();}
 @Transactional public void revokeAssignment(UUID id){AssessmentAssignmentEntity e=assignments.findById(id).orElseThrow(()->missing("ASSIGNMENT_NOT_FOUND","Không tìm thấy phân công"));e.status=AssessmentAssignmentStatus.REVOKED;e.updatedAt=Instant.now();}
 @Transactional public ExamResponse createCompetition(CompetitionRequest i){ExamRequest e=new ExamRequest(i.title(),null,null,AssessmentContextType.COMPETITION,null,true,i.durationMinutes(),i.opensAt(),i.closesAt(),i.maxAttempts(),0,i.passingScore(),true,true,ScoreStrategy.HIGHEST,ExamStatus.DRAFT,List.of());ExamResponse out=createExam(e);CompetitionEntity c=competitions.findById(out.id()).orElseGet(CompetitionEntity::new);c.assessmentId=out.id();c.registrationOpensAt=i.registrationOpensAt();c.registrationClosesAt=i.registrationClosesAt();c.leaderboardVisibility=i.leaderboardVisibility()==null?LeaderboardVisibility.AFTER_CLOSE:i.leaderboardVisibility();competitions.save(c);rewards.deleteAllByCompetitionId(out.id());if(i.rewards()!=null)for(RewardRequest r:i.rewards()){CompetitionRewardEntity x=new CompetitionRewardEntity();x.competitionId=out.id();x.rankFrom=r.rankFrom();x.rankTo=r.rankTo();x.rewardType=r.rewardType();x.rewardPayloadJson=json(r.payload());rewards.save(x);}return out;}
 @Transactional(readOnly=true) public List<LeaderboardEntry> leaderboard(UUID id){return leaderboard.findAllByCompetitionIdOrderByRankAsc(id).stream().map(e->new LeaderboardEntry(e.userId,e.attemptId,e.score,e.durationMs,e.submittedAt,e.rank)).toList();}
 @Transactional public void publishCompetition(UUID id){CompetitionEntity c=competitions.findById(id).orElseThrow(()->missing("COMPETITION_NOT_FOUND","Không tìm thấy cuộc thi"));c.resultStatus=CompetitionResultStatus.PUBLISHED;c.publishedAt=Instant.now();c.publishedBy=actor();}
}
