package com.lmspilot.identity.service;
import com.lmspilot.contracts.*; import com.lmspilot.identity.api.IdentityModels.*; import com.lmspilot.identity.domain.*; import com.lmspilot.support.api.ApiException; import com.lmspilot.support.security.CurrentUser; import java.time.Instant; import java.util.*; import java.util.stream.Collectors; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AuthorizationService {
 private final UserAccountRepository users; private final AuthorizationGrantRepository grants; private final ScopedRoleAssignmentRepository roleAssignments; private final RoleRepository roles; private final BulkOperationRepository operations;
 public AuthorizationService(UserAccountRepository users,AuthorizationGrantRepository grants,ScopedRoleAssignmentRepository roleAssignments,RoleRepository roles,BulkOperationRepository operations){this.users=users;this.grants=grants;this.roleAssignments=roleAssignments;this.roles=roles;this.operations=operations;}
 private UserAccountEntity user(UUID id){return users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Không tìm thấy tài khoản"));}
 public Set<String> capabilities(UUID userId){return permissionsForToken(user(userId));}
 public Set<String> permissionsForToken(UserAccountEntity user){return permissionsForToken(user,grants.findAllByPrincipalTypeAndPrincipalId(PrincipalType.USER,user.id),Instant.now());}
 public Map<UUID,Set<String>> permissionsForTokens(Collection<UserAccountEntity> source){if(source==null||source.isEmpty())return Map.of();Set<UUID>ids=source.stream().map(u->u.id).collect(Collectors.toSet());Map<UUID,List<AuthorizationGrantEntity>>byUser=grants.findAllByPrincipalTypeAndPrincipalIdIn(PrincipalType.USER,ids).stream().collect(Collectors.groupingBy(g->g.principalId));Instant now=Instant.now();Map<UUID,Set<String>>out=new LinkedHashMap<>();for(UserAccountEntity u:source)out.put(u.id,permissionsForToken(u,byUser.getOrDefault(u.id,List.of()),now));return out;}
 private Set<String> permissionsForToken(UserAccountEntity user,List<AuthorizationGrantEntity>direct,Instant now){Set<String> out=new LinkedHashSet<>();user.roles.forEach(r->out.addAll(r.permissions));for(AuthorizationGrantEntity g:direct){if(active(g.validFrom,g.validUntil,now)&&g.effect==GrantEffect.ALLOW)out.add(g.permissionCode);if(active(g.validFrom,g.validUntil,now)&&g.effect==GrantEffect.DENY)out.remove(g.permissionCode);}return Set.copyOf(out);}
 public Set<String> globalPermissionsForToken(UserAccountEntity user){return permissionsForToken(user);}
 private boolean active(Instant from,Instant until,Instant now){return (from==null||!from.isAfter(now))&&(until==null||until.isAfter(now));}
 @Transactional(readOnly=true) public EffectivePermissionResponse effective(UUID userId,ScopeType scopeType,UUID scopeId){Set<String> allowed=new LinkedHashSet<>(permissionsForToken(user(userId)));Set<String> denied=new LinkedHashSet<>();Instant now=Instant.now();for(AuthorizationGrantEntity g:grants.findAllByPrincipalTypeAndPrincipalId(PrincipalType.USER,userId)){boolean applies=g.scopeType==ScopeType.SYSTEM||g.scopeType==scopeType&&Objects.equals(g.scopeId,scopeId);if(applies&&active(g.validFrom,g.validUntil,now)){if(g.effect==GrantEffect.DENY){denied.add(g.permissionCode);allowed.remove(g.permissionCode);}else if(!denied.contains(g.permissionCode))allowed.add(g.permissionCode);}}return new EffectivePermissionResponse(userId,scopeType,scopeId,Set.copyOf(allowed),Set.copyOf(denied));}
 @Transactional(readOnly=true) public AuthorizationExplanationResponse explain(UUID userId,ScopeType scopeType,UUID scopeId){EffectivePermissionResponse e=effective(userId,scopeType,scopeId);List<PermissionSourceResponse> sources=new ArrayList<>();UserAccountEntity u=user(userId);for(RoleEntity r:u.roles)for(String p:r.permissions)sources.add(new PermissionSourceResponse(p,"ROLE",r.id,r.code,GrantEffect.ALLOW,ScopeType.SYSTEM,null,null,null,true,true));for(AuthorizationGrantEntity g:grants.findAllByPrincipalTypeAndPrincipalId(PrincipalType.USER,userId)){boolean a=active(g.validFrom,g.validUntil,Instant.now());boolean applies=g.scopeType==ScopeType.SYSTEM||g.scopeType==scopeType&&Objects.equals(g.scopeId,scopeId);sources.add(new PermissionSourceResponse(g.permissionCode,"GRANT",g.id,"Cấp quyền trực tiếp",g.effect,g.scopeType,g.scopeId,g.validFrom,g.validUntil,a,applies));}return new AuthorizationExplanationResponse(e,sources);}
 public boolean check(UUID userId,String permission,ScopeType scopeType,UUID scopeId){return effective(userId,scopeType,scopeId).allowed().contains(permission);}
 public Set<UUID> scopeIds(UUID userId,String permission,ScopeType scopeType){Set<UUID> out=new LinkedHashSet<>();if(permissionsForToken(user(userId)).contains(permission))return out;for(AuthorizationGrantEntity g:grants.findAllByPrincipalTypeAndPrincipalId(PrincipalType.USER,userId))if(g.permissionCode.equals(permission)&&g.effect==GrantEffect.ALLOW&&g.scopeType==scopeType&&g.scopeId!=null&&active(g.validFrom,g.validUntil,Instant.now()))out.add(g.scopeId);return out;}
 public List<RoleAssignmentResponse> assignments(UUID userId){return roleAssignments.findAllByUserIdOrderByCreatedAtDesc(userId).stream().map(a->new RoleAssignmentResponse(a.id,a.userId,a.role.code,a.scopeType,a.scopeId,a.effect,a.validFrom,a.validUntil)).toList();}
 public BulkGrantPreviewResponse previewBulk(BulkGrantPreviewRequest input){Set<String> requested=input.grants()==null?Set.of():input.grants().stream().map(g->g.permissionCode()!=null?g.permissionCode():g.roleCode()).filter(Objects::nonNull).collect(Collectors.toSet());List<UserGrantPreview> preview=new ArrayList<>();for(UUID id:input.userIds()){UserAccountEntity u=user(id);Set<String> current=permissionsForToken(u);Set<String> add=new LinkedHashSet<>(requested);add.removeAll(current);Set<String> duplicate=new LinkedHashSet<>(requested);duplicate.retainAll(current);preview.add(new UserGrantPreview(id,u.fullName,add,duplicate,Set.of(),Set.of()));}return new BulkGrantPreviewResponse(input.userIds().size(),input.userIds().size()*requested.size(),preview.stream().mapToInt(v->v.alreadyAllowed().size()).sum(),requested.stream().filter(p->p.contains("manage")||p.contains("write")||p.contains("grant")).collect(Collectors.toSet()),preview);}
 @Transactional public BulkGrantResponse grantBulk(BulkGrantRequest input){if(operations.existsById(input.operationId()))throw new ApiException(HttpStatus.CONFLICT,"DUPLICATE_OPERATION","Mã thao tác đã được sử dụng");List<GrantResponse> created=new ArrayList<>();int duplicates=0;for(UUID userId:input.userIds()){user(userId);for(GrantInput g:input.grants()){if(!g.hasExactlyOneSubject()||!g.validScope())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_GRANT","Cấu hình quyền không hợp lệ");if(g.roleCode()!=null)throw new ApiException(HttpStatus.CONFLICT,"EXCLUSIVE_ROLE_MODEL","LMSPilot chỉ cho phép một vai trò sản phẩm trên mỗi tài khoản; hãy đổi vai trò tài khoản thay vì cấp vai trò chéo");if(!PermissionCatalog.codes().contains(g.permissionCode()))throw new ApiException(HttpStatus.BAD_REQUEST,"UNKNOWN_PERMISSION","Permission không tồn tại");AuthorizationGrantEntity e=new AuthorizationGrantEntity();e.principalType=PrincipalType.USER;e.principalId=userId;e.permissionCode=g.permissionCode();e.scopeType=g.scopeType();e.scopeId=g.scopeId();e.effect=g.effect()==null?GrantEffect.ALLOW:g.effect();e.validFrom=g.validFrom();e.validUntil=g.validUntil();e.createdBy=CurrentUser.id();grants.save(e);created.add(new GrantResponse(e.id,e.principalType,e.principalId,e.permissionCode,e.scopeType,e.scopeId,e.effect,e.validFrom,e.validUntil));}}BulkOperationEntity op=new BulkOperationEntity();op.operationId=input.operationId();op.operationType="AUTHORIZATION_GRANT";op.requestedBy=CurrentUser.id();op.resultJson="{\"created\":"+created.size()+"}";operations.save(op);return new BulkGrantResponse(input.operationId(),created,List.of(),duplicates);}
 @Transactional public RevokeGrantsResponse revokeBulk(RevokeGrantsRequest input){if(!input.hasTarget())throw new ApiException(HttpStatus.BAD_REQUEST,"EMPTY_REVOKE","Không có quyền cần thu hồi");long g=grants.deleteAllByIdInAndPrincipalType(input.grantIds(),PrincipalType.USER);long r=roleAssignments.deleteAllByIdIn(input.roleAssignmentIds());return new RevokeGrantsResponse(g,r);}
}
