spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userOrIpKeyResolver}"
