package com.lmspilot.organization.api;
import com.lmspilot.contracts.Permissions;import com.lmspilot.organization.domain.*;import com.lmspilot.support.api.ApiException;import com.lmspilot.support.security.*;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class OrganizationService{
 private final OrganizationUnitRepository repository;private final ScopedAuthorizationClient scoped;public OrganizationService(OrganizationUnitRepository r,ScopedAuthorizationClient s){repository=r;scoped=s;}
 @Transactional(readOnly=true) public List<OrganizationUnitResponse> search(String query,OrganizationUnitStatus status){Set<UUID> visible=visibleUnitIds(Permissions.ORGANIZATION_READ);return repository.search(query==null||query.isBlank()?null:query,status).stream().filter(e->visible==null||visible.contains(e.getId())).map(e->response(e,List.of())).toList();}
 @Transactional(readOnly=true) public List<OrganizationUnitResponse> tree(){Set<UUID> visible=visibleUnitIds(Permissions.ORGANIZATION_READ);List<OrganizationUnitEntity> all=repository.findAll().stream().filter(e->visible==null||visible.contains(e.getId())).sorted(Comparator.comparingInt(OrganizationUnitEntity::getSortOrder).thenComparing(OrganizationUnitEntity::getName)).toList();Map<UUID,List<OrganizationUnitEntity>> grouped=all.stream().collect(Collectors.groupingBy(OrganizationUnitEntity::getParentId));return build(null,grouped);}
 private List<OrganizationUnitResponse> build(UUID parent,Map<UUID,List<OrganizationUnitEntity>> grouped){return grouped.getOrDefault(parent,List.of()).stream().map(n->response(n,build(n.getId(),grouped))).toList();}
 @Transactional public OrganizationUnitResponse create(OrganizationUnitRequest in){if(repository.existsByCodeIgnoreCase(in.code().trim()))throw duplicate();OrganizationUnitEntity parent=in.parentId()==null?null:repository.findById(in.parentId()).orElseThrow(this::parentNotFound);if(parent==null)requireGlobal(Permissions.ORGANIZATION_MANAGE);else requireUnitPermission(parent,Permissions.ORGANIZATION_MANAGE);String path=parent==null?"/":parent.getMaterializedPath()+parent.getId()+"/";return response(repository.save(new OrganizationUnitEntity(in.code().trim().toUpperCase(),in.name().trim(),in.type(),parent==null?null:parent.getId(),in.status(),in.sortOrder(),path)),List.of());}
 @Transactional public OrganizationUnitResponse update(UUID id,OrganizationUnitRequest in){OrganizationUnitEntity e=repository.findById(id).orElseThrow(this::notFound);requireUnitPermission(e,Permissions.ORGANIZATION_MANAGE);OrganizationUnitEntity parent=in.parentId()==null?null:repository.findById(in.parentId()).orElseThrow(this::parentNotFound);if(parent!=null)requireUnitPermission(parent,Permissions.ORGANIZATION_MANAGE);if(parent!=null&&(parent.getId().equals(e.getId())||parent.getMaterializedPath().contains("/"+e.getId()+"/")))throw new ApiException(HttpStatus.CONFLICT,"ORGANIZATION_CYCLE","Không thể chuyển đơn vị vào chính nó hoặc đơn vị con");String old=e.getMaterializedPath()+e.getId()+"/";String np=parent==null?"/":parent.getMaterializedPath()+parent.getId()+"/";e.setName(in.name().trim());e.setType(in.type());e.setParentId(parent==null?null:parent.getId());e.setStatus(in.status());e.setSortOrder(in.sortOrder());e.setMaterializedPath(np);e.setUpdatedAt(Instant.now());String prefix=np+e.getId()+"/";for(var d:repository.findAll())if(!d.getId().equals(e.getId())&&d.getMaterializedPath().startsWith(old)){d.setMaterializedPath(prefix+d.getMaterializedPath().substring(old.length()));d.setUpdatedAt(Instant.now());}return response(e,List.of());}
 @Transactional public OrganizationUnitResponse deactivate(UUID id){OrganizationUnitEntity e=repository.findById(id).orElseThrow(this::notFound);requireUnitPermission(e,Permissions.ORGANIZATION_MANAGE);e.setStatus(OrganizationUnitStatus.INACTIVE);e.setUpdatedAt(Instant.now());return response(e,List.of());}
 private Set<UUID> visibleUnitIds(String permission){if(isGlobal(permission))return null;Set<UUID> roots=new HashSet<>();for(String t:List.of("BRANCH","DEPARTMENT","GROUP")){roots.addAll(scoped.scopeIds(permission,t));roots.addAll(scoped.scopeIds(Permissions.ORGANIZATION_MANAGE,t));}if(roots.isEmpty())return Set.of();return repository.findAll().stream().filter(u->roots.stream().anyMatch(r->u.getId().equals(r)||u.getMaterializedPath().contains("/"+r+"/"))).map(OrganizationUnitEntity::getId).collect(Collectors.toSet());}
 private void requireGlobal(String p){if(!isGlobal(p))throw new ApiException(HttpStatus.FORBIDDEN,"ORGANIZATION_OUT_OF_SCOPE","Cần quyền toàn hệ thống cho thao tác này");}
 private void requireUnitPermission(OrganizationUnitEntity u,String p){if(isGlobal(p))return;List<String> c=switch(u.getType()){case BRANCH->List.of("BRANCH");case DEPARTMENT,DIVISION->List.of("DEPARTMENT","BRANCH");default->List.of("GROUP","DEPARTMENT","BRANCH");};boolean ok=c.stream().anyMatch(t->scoped.allowed(p,t,u.getId()))||c.stream().anyMatch(t->scoped.allowed(Permissions.ORGANIZATION_WRITE,t,u.getId()));if(!ok)throw new ApiException(HttpStatus.FORBIDDEN,"ORGANIZATION_OUT_OF_SCOPE","Đơn vị ngoài phạm vi được cấp");}
 private boolean isGlobal(String p){return CurrentUser.hasRole("ADMIN")||CurrentUser.authorities().contains(p)||CurrentUser.authorities().contains(Permissions.ORGANIZATION_MANAGE)||CurrentUser.authorities().contains(Permissions.ORGANIZATION_WRITE)||scoped.allowed(p,"SYSTEM",null)||scoped.allowed(Permissions.ORGANIZATION_WRITE,"SYSTEM",null);}
 private ApiException duplicate(){return new ApiException(HttpStatus.CONFLICT,"DUPLICATE_ORGANIZATION_CODE","Mã đơn vị đã tồn tại");}private ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"ORGANIZATION_NOT_FOUND","Không tìm thấy đơn vị");}private ApiException parentNotFound(){return new ApiException(HttpStatus.BAD_REQUEST,"PARENT_NOT_FOUND","Đơn vị cha không tồn tại");}
 static OrganizationUnitResponse response(OrganizationUnitEntity e,List<OrganizationUnitResponse> c){return new OrganizationUnitResponse(e.getId(),e.getCode(),e.getName(),e.getType(),e.getParentId(),e.getStatus(),e.getSortOrder(),e.getMaterializedPath(),c);}
}
