package com.lmspilot.organization.api;
import com.lmspilot.contracts.Permissions;import com.lmspilot.organization.domain.*;import com.lmspilot.support.api.ApiException;import com.lmspilot.support.security.*;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class OrganizationMembershipService{private final OrganizationMembershipRepository memberships;private final OrganizationUnitRepository units;private final ScopedAuthorizationClient scoped;public OrganizationMembershipService(OrganizationMembershipRepository m,OrganizationUnitRepository u,ScopedAuthorizationClient s){memberships=m;units=u;scoped=s;}
 @Transactional(readOnly=true) public List<MembershipResponse> byUser(UUID id){return memberships.findAllByUserIdOrderByCreatedAtDesc(id).stream().map(OrganizationMembershipService::response).toList();}
 @Transactional(readOnly=true) public List<MembershipResponse> byUnit(UUID id){var u=requireUnit(id);requireUnitPermission(u,Permissions.ORGANIZATION_READ);return memberships.findAllByUnitIdOrderByCreatedAtDesc(id).stream().map(OrganizationMembershipService::response).toList();}
 @Transactional(readOnly=true) public List<MembershipResponse> byUserForRequester(UUID id){var rows=memberships.findAllByUserIdOrderByCreatedAtDesc(id);if(isGlobal(Permissions.ORGANIZATION_READ))return rows.stream().map(OrganizationMembershipService::response).toList();Map<UUID,OrganizationUnitEntity> map=new HashMap<>();for(var u:units.findAllById(rows.stream().map(OrganizationMembershipEntity::getUnitId).collect(Collectors.toSet())))map.put(u.getId(),u);return rows.stream().filter(r->map.containsKey(r.getUnitId())&&canAccessUnit(map.get(r.getUnitId()),Permissions.ORGANIZATION_READ)).map(OrganizationMembershipService::response).toList();}
 @Transactional public List<MembershipResponse> grant(BulkMembershipRequest in){Set<UUID> ids=in.memberships().stream().map(MembershipInput::unitId).collect(Collectors.toSet());Map<UUID,OrganizationUnitEntity> found=new HashMap<>();for(var u:units.findAllById(ids))found.put(u.getId(),u);if(found.size()!=ids.size())throw new ApiException(HttpStatus.BAD_REQUEST,"UNIT_NOT_FOUND","Một hoặc nhiều đơn vị không tồn tại");found.values().forEach(u->requireUnitPermission(u,Permissions.ORGANIZATION_MEMBERSHIP_MANAGE));List<OrganizationMembershipEntity> created=new ArrayList<>();for(var item:in.memberships()){if(memberships.existsByUserIdAndUnitIdAndMembershipType(item.userId(),item.unitId(),item.membershipType()))continue;if(item.primaryMembership())memberships.findAllByUserIdOrderByCreatedAtDesc(item.userId()).stream().filter(OrganizationMembershipEntity::isPrimaryMembership).forEach(x->x.setPrimaryMembership(false));created.add(memberships.save(new OrganizationMembershipEntity(item.userId(),item.unitId(),item.membershipType(),item.primaryMembership(),item.validFrom(),item.validUntil(),CurrentUser.id())));}return created.stream().map(OrganizationMembershipService::response).toList();}
 @Transactional public Map<String,Long> revoke(RevokeMembershipRequest in){var rows=memberships.findAllById(in.membershipIds());if(rows.size()!=in.membershipIds().size())throw new ApiException(HttpStatus.NOT_FOUND,"MEMBERSHIP_NOT_FOUND","Một hoặc nhiều liên kết thành viên không tồn tại");Map<UUID,OrganizationUnitEntity> map=new HashMap<>();for(var u:units.findAllById(rows.stream().map(OrganizationMembershipEntity::getUnitId).collect(Collectors.toSet())))map.put(u.getId(),u);for(var r:rows){var u=map.get(r.getUnitId());if(u==null)throw new ApiException(HttpStatus.NOT_FOUND,"UNIT_NOT_FOUND","Đơn vị không tồn tại");requireUnitPermission(u,Permissions.ORGANIZATION_MEMBERSHIP_MANAGE);}return Map.of("deleted",memberships.deleteAllByIdIn(in.membershipIds()));}
 @Transactional(readOnly=true) public Set<UUID> descendants(UUID id){var root=requireUnit(id);String marker="/"+root.getId()+"/";return units.findAll().stream().filter(u->u.getId().equals(id)||u.getMaterializedPath().contains(marker)).map(OrganizationUnitEntity::getId).collect(Collectors.toSet());}
 @Transactional(readOnly=true) public Set<UUID> ancestors(UUID id){var u=requireUnit(id);Set<UUID> out=Arrays.stream(u.getMaterializedPath().replaceAll("^/+|/+$","").split("/")).filter(s->!s.isBlank()).map(UUID::fromString).collect(Collectors.toSet());out.add(u.getId());return out;}
 @Transactional(readOnly=true) public Set<UUID> usersInScope(UUID id){Set<UUID> unitIds=descendants(id);Instant now=Instant.now();return memberships.findAllByUnitIdIn(unitIds).stream().filter(m->(m.getValidFrom()==null||!m.getValidFrom().isAfter(now))&&(m.getValidUntil()==null||m.getValidUntil().isAfter(now))).map(OrganizationMembershipEntity::getUserId).collect(Collectors.toSet());}
 private OrganizationUnitEntity requireUnit(UUID id){return units.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"UNIT_NOT_FOUND","Không tìm thấy đơn vị"));}
 private void requireUnitPermission(OrganizationUnitEntity u,String p){if(!canAccessUnit(u,p))throw new ApiException(HttpStatus.FORBIDDEN,"ORGANIZATION_MEMBERSHIP_OUT_OF_SCOPE","Đơn vị ngoài phạm vi quản lý thành viên");}
 private boolean canAccessUnit(OrganizationUnitEntity u,String p){if(isGlobal(p))return true;List<String> c=switch(u.getType()){case BRANCH->List.of("BRANCH");case DEPARTMENT,DIVISION->List.of("DEPARTMENT","BRANCH");default->List.of("GROUP","DEPARTMENT","BRANCH");};return c.stream().anyMatch(t->scoped.allowed(p,t,u.getId()))||c.stream().anyMatch(t->scoped.allowed(Permissions.ORGANIZATION_MANAGE,t,u.getId()));}
 private boolean isGlobal(String p){return CurrentUser.hasRole("ADMIN")||CurrentUser.authorities().contains(p)||CurrentUser.authorities().contains(Permissions.ORGANIZATION_MANAGE)||scoped.allowed(p,"SYSTEM",null)||scoped.allowed(Permissions.ORGANIZATION_MANAGE,"SYSTEM",null);}
 static MembershipResponse response(OrganizationMembershipEntity m){Instant n=Instant.now();boolean a=(m.getValidFrom()==null||!m.getValidFrom().isAfter(n))&&(m.getValidUntil()==null||m.getValidUntil().isAfter(n));return new MembershipResponse(m.getId(),m.getUserId(),m.getUnitId(),m.getMembershipType(),m.isPrimaryMembership(),m.getValidFrom(),m.getValidUntil(),a,m.getCreatedAt());}
}
